config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  
  resources :articles do
  	resources :comments
  end
  
  get 'tags/:tag', to: 'articles#index', as: :tag, :constraints  => { :tag => /[^\/]+/ }
  
  devise_for :users
  	resources :users
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments, dependent: :destroy
	belongs_to :user
	validates :title, presence: true, 
										length: { minimum: 5 }

	has_many :taggings
  has_many :tags, through: :taggings

  def self.tagged_with(name)
    Tag.find_by!(name: name).articles
  end

  def self.tag_counts
    Tag.select('tags.*, count(taggings.tag_id) as count').joins(:taggings).group('taggings.tag_id')
  end

  def tag_list
    tags.map(&:name).join(', ')
  end

  def tag_list=(names)
    self.tags = names.split(',').map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end

	def self.search(search)
	  if search
	    self.where('title ILIKE ? OR text ILIKE ?', "%#{search}%", "%#{search}%")
	  else
	    self
	  end
	end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :taggings
  has_many :articles, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles
  has_many :comments
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article ,only: [:edit, :update, :show, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    @articles = if params[:tag]
      @articles = Article.tagged_with(params[:tag])
    else
      @articles = Article.all
    end
    if params[:search].present?
      @articles = @articles.search(params[:search])
    end
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    #render plain: params[:article].inspect
    @article = Article.new(article_params)
    if @article.save
      flash[:success] = "Article was successfully created"
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
      flash[:success] = "Article was successfully updated"
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.taggings.where(:article => params[:id]).first.destroy
    @article.destroy
      flash[:danger] = "Article was successfully destroyed"
    redirect_to articles_path
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :text, :user_id, :tag_list, :search)
    end 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def show
		@article = Article.find(params[:id])
		@comment = @article.comments.find(params[:id])
	end

	def create
		@article = Article.find(params[:article_id])
		@comment = @article.comments.create(comment_params)
			flash[:success] = "Comment was successfully created"
		redirect_to article_path(@article)
	end
	def destroy
		@article = Article.find(params[:article_id])
		@comment = Comment.all.where(:article => params[:id]).first
		@comment.destroy
			flash[:danger] = "Comment was successfully destroyed"
		redirect_to article_path
	end
	
	private
		def comment_params
			params.require(:comment).permit(:commenter, :body, :user_id, :article_id)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:edit, :update, :show]
	def index
		@users = User.all
	end
  
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		flash[:success] = "Welcome to the alpha blog #{@user.username}"
  		redirect_to articles_path
  	else
  		render 'new'
  	end
  end

  def edit
  end

  def update
  	if @user.update(user_params)
  		flash[:success] = "Your account was updated successfully" 
  		redirect_to articles_path
  	else
  		render 'edit'
  	end
  end

  def show
    @user = User.find(params[:id])
  end

  private
    def user_params
    	params.require(:user).permit(:name, :email, :password)
    end

	def set_user
		@user = User.find(params[:id])
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tag_helper.rb
module TagHelper
  def tag_cloud(tags, classes)
    max = tags.sort_by(&:count).last
    tags.each do |tag|
      index = tag.count.to_f / max.count * (classes.size - 1)
      yield(tag, classes[index.round])
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_article.html.erb
<%if obj.present?%>
	<% obj.each do |article| %>
		<div class="row">
			<div class="col-xs-8 col-xs-offset-2">
				<div class="well well-lg">
					<div class="article-title">
						<h3><%= link_to article.title, article_path(article) %></h3>
					</div>
					<div class="article-body">
						<%= truncate(article.text, length: 100)%>
						<div class="article-meta-details">
							<h6 class="btn btn-xs btn-info"><%= link_to("Created by: #{article.user.name}", user_path(article.user)) if article.user%></h6><br>
							<small>
								Created at:<%= time_ago_in_words(article.created_at) %> ago | Last updated: <%= time_ago_in_words(article.updated_at) %> ago
							</small>
						</div>
					</div>
		<% if user_signed_in? && current_user == article.user %>
			<div class="article-actions">
				<%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %> 
				<%= link_to "Delete this article", article_path(article), method: :delete, 
																						data: {confirm: "Are you sure you want to delete the article?"},
																						class: "btn btn-xs btn-danger" %>
			</div>
		<% end %>
					<div class="btn-group">
						<div class="article-actions">
						  <span class="btn btn-xs btn-warning dropdown-toggle" >Tags</span>
						  <span><%= raw article.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %></span>
						</div>
					</div>

				</div>
			</div>
		</div>
	<% end %>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/error', obj: @article %>

<div class="row">
  <div class="col-xs-12">
    <%= form_for(@article, html: {class: "form-horizontal", role:"form"}) do |f| %>
      <div class='form-group'>
        <div class='control-label col-sm-2'>
          <%= f.label :title %>
        </div>

        <div class='col-sm-8'>
          <%= f.text_field :title, class:'form-control', placeholder: "Title of article", autofocus: true %>
        </div>
      </div>
      
      <div class='form-group'>
        <div class='control-label col-sm-2'>
          <%= f.label :text %>
        </div>

        <div class='col-sm-8'>
          <%= f.text_area :text, rows: 10, class:'form-control', placeholder: "Body of article", autofocus: true %>
        </div>
      </div>

      <div class='form-group'>
        <div class='control-label col-sm-2'>
          <%= f.label :tag_list, "Tags (separated by commas)" %>
        </div>

        <div class='col-sm-8'>
          <%= f.text_field :tag_list, class:'form-control', placeholder: "Enter Tag for this article", autofocus: true %>
        </div>
      </div>

      <%= f.hidden_field :user_id, :value => current_user.id %>
      
      <div class='form-group'>
        <div class='col-sm-offset-2 col-sm-10'>
          <%= f.submit class: 'btn btn-primary btn-lg' %>
        </div>
      </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
      [ <%= link_to "Cancel to request and return to articles listing", articles_path %> ]
  </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Edit article</h1>
 
<%= render 'form' %>
 

app/views/articles/index.html.erb
<div class="container">
  <h1 align="center">Hoang's Blog</h1>
  <h2 align="center">My first Rails Application for CoderSchool</h2>
  <h2 align="center">Listing all articles</h2>

   <%= render 'article', obj: @articles%>
  <br>
</div> 

app/views/articles/new.html.erb
<div class="container">
	<h1 align="center">Create an article</h1>
	<%= render 'form' %>
</div>

app/views/articles/show.html.erb
<%if @article.present?%>	
	<div class="row">
		<div class="col-xs-9 col-xs-offset-2">
			<div class="well well-lg">
				<div class="article-title">
				  <h3><%= @article.title %></h3>
	  		</div>

	 			<div class="article-text">
	  			<h6><%= @article.text %></h6>
	  		</div>

	  		<div class="article-text">
		  		<h3> Add a comment: </h3>
					<%= render 'comments/form' %>
	  		</div>

	  		<% @article.comments.order("created_at DESC").each do |comment| %>
	  			<%if comment.user.present?%>
		  			<div class="row">
	      			<div class="col-xs-8 col-xs-offset-2">
		     				<div class="well well-sm">
							  	<h6> Comment :<%= comment.body %></h6> 
					  					<div class="article-text">
												<h6 class="btn btn-xs btn-info"><%= link_to("Commented by: #{comment.user.name}", article_comment_path(@article.comments)) if @article.user %></h6><br/>
												<small >Created at:<%= time_ago_in_words(comment.created_at) %> ago | Last updated: <%= time_ago_in_words(comment.updated_at) %> ago</small>
												<% if user_signed_in? && current_user == comment.user%>
													<div class="article-actions">
													<%= link_to "Edit this comment", edit_article_comment_path(comment), class: "btn btn-xs btn-primary" %> 
													<%= link_to "Delete this comment", article_comment_path(comment), method: :delete, 
																										data: {confirm: "Are you sure you want to delete the article?"},
																										class: "btn btn-xs btn-danger" %>
								
													</div>
												<% end %>
											</div>
					  		</div>
				  		</div>
				  	</div>
				  <% end %>
		  	<% end %>


				
			</div>
	  	</div>
	  </div>
	</div>
<% end %>

<%= link_to 'Edit', edit_article_path(@article) %>  |
<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
 
<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<div class='row'>
  <div class='col-xs-12'>
		<%= form_with(model: [ @article, @article.comments.build ], html: {class: "form-horizontal", role:"form"}, local: true) do |f| %>
 			<div class='form-group'>

			<div class='form-group'>
	      <div class='control-label col-sm-2'>
			  	<%= f.label :body %>
				</div>

				<div class='col-sm-8'>
			  	<%= f.text_area :body, class:'form-control', placeholder: "Enter comment" %>
				</div>
	  	</div>

        <%= f.hidden_field :user_id, :value => current_user.id %>

		  <div class='form-group'>
	      <div class='col-sm-offset-2 col-sm-10'>
			  	<%= f.submit class: 'btn btn-primary btn-lg' %>
				</div>
		  </div>
		<% end %>
	</div>
</div>

app/views/layouts/_message.html.erb
<div class='row'>
	<div align="center" class='col-xs-9 col-xs-offset-2'>
		<% flash.each do |name, msg| %>
			<div class='alert alert-<%="#{name}"%>'>
				<a href='#' class='close' date-dismiss='alert'>&#215;</a>
				<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
			</div>
		<% end %>
	</div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Hoang's blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articles", articles_path %>
        <li><%= link_to "Users", users_path %></li>
        <% if user_signed_in? %>
          <li>
            <%= link_to "New article", new_article_path %>
          </li>
        <% end %>
      </ul>

      <form class="navbar-form navbar-left">
        <div class="form-group">
          <%= form_tag articles_path, :class =>"form-control", :method => 'get' do %>
          <%= text_field_tag :search, params[:search], :class =>"form-control" %>
          <%= submit_tag "Search", :class => "btn btn-default" %>
          <% end %>
        </div>
      </form>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit your profile", edit_user_path(current_user)%></li>
              <li><%= link_to "View your profile", user_path(current_user)%></li>
            </ul>
          </li>
          <% else %>
          <li><%= link_to "Log in", user_session_path %></li>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <% end %>  
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	 	<%= render "layouts/navigation" %> 
    	<%= render "layouts/message" %>   

  	<%= yield %>
    <%= debug(params) if Rails.env.development? %>

  </body>


</html>

app/views/shared/_error.html.erb
<%if obj.present?%>
  <%if obj.errors.any? %>
    <div class='row'>
      <div class='col-xs-8 col-xs-offset-2'>
        <div class='panel panel-danger'>
          <div class="panel-heading">
            <h2 class='panel-title'>
              <%= pluralize(obj.errors.count, "error")%> prohibited this article from being saved:
            </h2>
            <div class="panel-body">
            	<ul>
    			  		<% obj.errors.full_messages.each do |msg| %>
    							<li><%= msg %></li>
    			  		<% end %>
  						</ul>
  		  		</div>
  				</div>
  	  	</div>
  		</div>
    </div>
  <% end %>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/error', obj: @user %>

<div class='row'>
  <div class='col-xs-12'>
    <%= form_for(@user, html: {class: "form-horizontal", role:"form"}) do |f| %>
      <div class='form-group'>
      	<div class='control-label col-sm-2'>
		  		<%= f.label :name %>
				</div>

				<div class='col-sm-8'>
		  		<%= f.text_field :name, class:'form-control', placeholder: "Enter username", autofocus: true %>
				</div>
	  	</div>

		  <div class='form-group'>
	      <div class='control-label col-sm-2'>
			  	<%= f.label :email %>
				</div>

				<div class='col-sm-8'>
			  	<%= f.email_field :email, class:'form-control', placeholder: "Enter email" %>
				</div>
		  </div>

		  <div class='form-group'>
	      <div class='control-label col-sm-2'>
			  	<%= f.label :password %>
				</div>

				<div class='col-sm-8'>
			  	<%= f.password_field :password, class:'form-control', placeholder: "Enter password" %>
				</div>
		  </div>
		  <div class='form-group'>
	      <div class='col-sm-offset-2 col-sm-10'>
	      	<p>
      			<% if @user.new_record? %>
        			<%= f.submit "Create Account", class: 'btn btn-primary btn-lg' %>
      			<% else %>
        			<%= f.submit "Update Account", class: 'btn btn-primary btn-lg' %>
      			<% end %>
    			</p>
				</div>
		  </div>

		<% end %>
		<div class="col-xs-4 col-xs-offset-4">
			[ <%= link_to "Cancel to request and return to articles listing", articles_path %> ]
		</div>
	</div>
</div>

app/views/users/edit.html.erb
<h1 align="center"> Edit your account </h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">All Hoang's Bloggers</h1>
<div align="center">
	<% @users.each do |user|%>
		<ul class="listing">
			<div class="row">
				<div class="well col-md-4 col-md-offset-4">
					<li class="article-title">
						<%= link_to user.name, user_path(user) %>
					</li>
					<li><small><%= pluralize(user.articles.count, "article") if user.articles %>	</small></li>
				</div>
			</div>
		</ul>
	<% end %>
</div>

app/views/users/new.html.erb
<h1 align="center"> Signup for Hoang's Blog </h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center"> Welcome to <%=@user.name%>'s page'</h1>

<h2 align="center"><%= @user.name %>'s articles </h2>

<%= render 'articles/article', obj: @user.articles%>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to "My Blog", controller: "articles" %>